crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud/', include('crudOperations.urls', namespace='crud'))
]

crud/crudOperations/urls.py
from django.urls import path
from .views import (list_all_user, detail_of_user, create_user_info, update_user_info, delete_user_info)


app_name = 'crud'

urlpatterns = [
    # crud/list/
    # {% url 'crud:list' %}
    path('list/', list_all_user, name='list'),
    path('create/', create_user_info, name='create'),
    path('detail/<int:user_id>/', detail_of_user, name='detail'),
    path('update/<int:user_id>/', update_user_info, name='update'),
    path('delete/<int:user_id>/', delete_user_info, name='delete'),
]

crud/crudOperations/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    dob = models.DateField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

crud/crudOperations/forms.py
from django.forms import ModelForm
from .models import UserInfo


class UserInfoModelForm(ModelForm):
    class Meta:
        model = UserInfo
        fields = ['first_name', 'middle_name', 'last_name', 'email', 'dob', 'bio']

crud/crudOperations/views.py
from django.shortcuts import render

# custom import
from django.shortcuts import get_object_or_404, redirect
from .models import UserInfo
from .forms import UserInfoModelForm


# Create your views here.
def list_all_user(request):
    data = UserInfo.objects.all()
    context = {
        'data': data
    }
    return render(request, "crudOperations/list.html", context=context)


def detail_of_user(request, user_id):
    user_object = get_object_or_404(UserInfo, id=user_id)
    context = {
        'user_object': user_object
    }
    return render(request, "crudOperations/detail.html", context=context)


def create_user_info(request):
    if request.method == 'POST':
        # process the form
        form_instance = UserInfoModelForm(request.POST)
        if form_instance.is_valid():
            form_instance.save()
            return redirect('/crud/list/')
        else:
            print("Form is invalid")
    else:
        form_instance = UserInfoModelForm()
    context = {
        'form_instance': form_instance
    }
    return render(request, 'crudOperations/create.html', context=context)


def update_user_info(request, user_id):
    user_object = get_object_or_404(UserInfo, id=user_id)
    if request.method == 'POST':
        # process the form
        form_instance = UserInfoModelForm(request.POST, instance=user_object)
        if form_instance.is_valid():
            form_instance.save()
            return redirect(f'/crud/detail/{user_id}')
        else:
            print("Form is invalid")
    else:
        form_instance = UserInfoModelForm(instance=user_object)
    context = {
        'form_instance': form_instance
    }
    return render(request, 'crudOperations/update.html', context=context)


def delete_user_info(request, user_id):
    user_object = get_object_or_404(UserInfo, id=user_id)
    # deleting the user object
    user_object.delete()

    return redirect(f'/crud/list/')

crud/crudOperations/templates/crudOperations/create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create UserInfo</title>

    <style>
        form{
            font-size: 20px;
        }
    </style>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form_instance.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

crud/crudOperations/templates/crudOperations/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Detail of User</title>

    <style>
        body{
            font-size: 20px;
        }
    </style>
</head>
<body>
    <h1>Detail of User:</h1>
First Name: {{ user_object.first_name }}
<br>
<br>
Middle Name:
    {% if user_object.middle_name %}
        {{ user_object.middle_name }}
    {% else %}
        (middle name not found)
    {% endif %}
<br>
<br>
Last Name:  {{ user_object.last_name }}
<br>
<br>
Email:  {{ user_object.email }}
<br>
<br>
Date of Birth:  {{ user_object.dob }}
<br>
<br>
BIO:  {{ user_object.bio }}
<br>
<br>

    <hr>
    <a href="/crud/list/">Go Back</a>
</body>
</html>

crud/crudOperations/templates/crudOperations/list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Info List</title>

    <style>
        body {
            font-size: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            text-align: center;
        }

        tr {

        }

        table, th, td {
            border: 1px solid forestgreen;
            padding: 10px;
        }
    </style>
</head>
<body>

<p>
    <a href="{% url 'crud:create' %}">Create New User</a>
</p>

<br>
<br>
<h1>List of all Users:</h1>

<table>
<tr>
    <th>Id</th>
    <th>First Name</th>
    <th>Middle Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Action</th>
</tr>
    {% for user_data in data %}
        <tr>
            <td>{{ user_data.id }}</td>
            <td>{{ user_data.first_name }}</td>
            <td>
                {% if user_data.middle_name %}
                    {{ user_data.middle_name }}
                {% else %}
                    -
                {% endif %}
            </td>
            <td>{{ user_data.last_name }}</td>
            <td>{{ user_data.email }}</td>
            <td>
                <a href="{% url 'crud:detail' user_data.id %}">Detail</a> /
                <a href="{% url 'crud:update' user_data.id %}">Update</a> /
                <a href="{% url 'crud:delete' user_data.id %}">Delete</a>
            </td>
        </tr>
    {% endfor %}

</table>
</body>
</html>

crud/crudOperations/templates/crudOperations/update.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Update UserInfo</title>

    <style>
        form{
            font-size: 20px;
        }
    </style>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form_instance.as_p }}
        <button type="submit">Update</button>
    </form>
</body>
</html>